version: '2'
services:
  db:
    build: db/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    container_name: django_db
    networks:
      - my-net

  web:
    build: .
    container_name: django_project
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
